### ISSUE TITLE
In 01-prerequisites.md, it is inferred you need to pay google money.

### ISSUE THREAD

**Issue by Ryonez** [Artemmkin/infrastructure-as-code-tutorial#15]
In this line:
```
You can sign up for $300 in free credits, which will be more than sufficient to complete all of the labs in this tutorial.
```
it is inferred you need funds for the Google Cloud Platform. While you *can* apply for the free credits, it does not guarantee that it'll be approved. I've tried myself, informing them I wish to learn more about the platform as a new coder and was denied.

I feel that what is needed, such as paid services, should be made a little more clear.

**Comment by Artemmkin** [comment]
hi @Ryonez , did you apply for a free trial? the last time I checked (about 9 months ago), getting a free trial was easy and you only had to provide your credit card info to prove you're not a robot, there certainly was no approval process

**Comment by Ryonez** [comment]
Yup. I've done some work with google's API's before as well, the account has a card tied to it and is used everyday. Even so:

![image](https://user-images.githubusercontent.com/16157130/48309054-07b71080-e5d6-11e8-8971-c7db09891fd9.png)

So no, it's not available to everyone sadly.

**Comment by Artemmkin** [comment]
@Ryonez did you try to register a new account which gives [$300 during the free trial](https://cloud.google.com/free/)?  This email kind of made me think you might've tried to apply for extra credit or something for an existing account

**Comment by Ryonez** [comment]
At the time I was working on my Gitlab server and wanted to look into Kubernetes.

`Get seamless integration with GKE and $500 credit for your project
Every new Google Cloud Platform account receives $300 in credit upon signup. In partnership with Google, GitLab is able to offer an additional $200 for new GCP accounts to get started with GitLab’s GKE integration. Here's a link to apply for your $200 credit.`
https://about.gitlab.com/2018/04/05/gke-gitlab-integration/

Same rules basically. And given I was denied for wanting to try out what it was for, I was kinda annoyed. I won't bother trying "free credit" now, as they seem to have some hidden additional requirements.

**Comment by Artemmkin** [comment]
yeah, it looks like you applied for an extra credit, so it's a different thing. In the docs, I'm talking about the free trial and $300 you receive on signup and it doesn't seem like there is a problem getting that.

**Comment by Ryonez** [comment]
`Every new Google Cloud Platform account receives $300 in credit upon signup`
This is the same thing you are referring to. $300 dollars starter credit.

`In partnership with Google, GitLab is able to offer an additional $200 for new GCP accounts to get started with GitLab’s GKE integration.`
Given what I was trying to do at the time, I was eligible for extra on top of that. I was still denied.

To me it doesn't matter there is addition credit, as that was denied as well, despite the use case for trying exactly what the credit was meant for.

Now, the title subject is still what I'm pointing out here. "it is inferred you need to pay google money". This is still true, you are assuming everyone will get, have the right of access to the $300 dollar starter pack. 

That's a bad thing to make a tutorial with. People might get denied, or have already used it.
